efault: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") || localhost %>
  port: <%= ENV.fetch("DATABASE_PORT") || 5433 %>
  username: <%= ENV.fetch("DATABASE_USER") || postgres %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") || postgres %>

development:
  <<: *default
  database: transactions_api_development

test:
  <<: *default
  database: transactions_api_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") || transactions_api_production %>
