name: Deploy with Capistrano

on:
  push:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Deploy Master
        env:
          DEPLOY_ENC_KEY: ${{ secrets.DEPLOY_ENC_KEY }}
        run: |
          openssl enc -d -aes-256-cbc -md sha512 -salt -in config/deploy_id_rsa_enc -out config/deploy_id_rsa -k $DEPLOY_ENC_KEY -a -pbkdf2
          chmod 600 config/deploy_id_rsa
          eval "$(ssh-agent -s)"
          ssh-add config/deploy_id_rsa
          gem install capistrano
          bundle exec cap production deploy
